### ISSUE TITLE
New workflow 

### ISSUE THREAD

**Issue by swewers** [MCLF/mclf#67]
In my opinion, the current workflow and in particular the role of the _develop_ branch is not optimal. The main problem I see is that it is not clear when changes made at some point to the _develop_ branch are 'stable' enough to go into the _master_ branch, and how this should be done. I suggest a slightly more involved branching model. 

### The main branches 
These are the main permanent branches on the MCLF/mclf repository.
- the _master_ branch: this is the current stable version that users should download. One could also think of it as the latest stable release. 
- the _develop_ branch: this is the branch hosting the most recent state of the project. We try to keep it stable. Sort of the beta version of the next release. It should always be possible to merge it into the master branch without merge conflicts.
- the _experimental_ branch: it points to a version with experimental changes for which it is not clear if or when they should be incorporated in the stable version. When one of these changes is deemed worthwhile and stable, it can be merged into _develop_ by cherry picking. 

An alternative would be to allow several experimental branches, one for each change. 

### Topics branches
These are typically hosted on one of our private repositories. They are created by pulling from the _develop_ branch. There are two types:
- _bug fixes_ :  depending on the type of bug, the fix is merged into _develop_, or both into _develop_ and _master_  (could this create problems when one later merges _develop_ into _master_?).
- _new features_ : when ready, these are merged into _develop_

**TODO**:
* [ ] Document this in our [README](./README.md)
* [ ] Merge develop into master, revert #15, and create a release.

**Comment by saraedum** [comment]
I'd recommend to drop the master branch from your proposal and use master for what you called develop and develop for what you called experimental; I think that this was mostly my original idea. The stable release is available by clicking on "Releases". master tracks the "beta" for the next release. develop tracks experimental changes. (We can also rename it to experimental, I can see that this might be a more natural name.) When we decide that master is stable enough, which is most of the time the case anyway, then we create a new release.
I agree with what you write about topic branches.

Why not have a dedicated master branch?
* Because it creates more bureaucracy and conflicts.
* When someone external comes to this page, they'll create a Pull Request against the default branch master; which might be the wrong target.
* When writing a bug fix, what's the target branch in your model? If it's master, then you can merge it and merge master into develop (but you might see conflicts.) If it's develop, then it's not part of the stable release...but I guess we'd always want a new release with every bugfix.

**Comment by saraedum** [comment]
Another remark about the develop/experimental branch. You don't need to create Pull Requests to merge your changes into it. You can just push to it directly. It depends a bit on your setup but something like `git push origin HEAD:develop` should work to push the changes on your local branch to the develop branch of mclf. There is nothing wrong about creating pull requests of course.

**Comment by swewers** [comment]
Ok, this makes sense. I guess my problem with the model so far is that I mostly used the develop branch for integrating new features, and I worry about getting these features into master at some later point. But this was then just the wrong choice. I think except for the temporary fix for issue #15 (which should not go into master because it will be obsolete once  #25397 and #25607 are part of Sage) all my pull requests could have also gone into master as well. Do you agree?

So I will try to get the things which look stable from develop into master one of these days, and then rename develop into experimental.

**Comment by swewers** [comment]
> Another remark about the develop/experimental branch. You don't need to create Pull Requests to merge your changes into it. You can just push to it directly. It depends a bit on your setup but something like git push origin HEAD:develop should work to push the changes on your local branch to the develop branch of mclf. There is nothing wrong about creating pull requests of course.

I like pull requests! It is very convenient that you try if it merges well and if the doctests pass, and if not push new version into it before merging.

**Comment by saraedum** [comment]
Yes, I agree to what you say. So let me pull develop into master and revert #15.
